// create offset wallets for T address rotation.
// Each address is considered one time use, if it receives less than 15000 zatoshi balance will be essentially burned.
//
// This class takes address index as constructor, and will create 10 addresses by default, if any of the addresses gets used
// it will be moved out of the pool
//
// T addresses are generated by creating new wallets with an extra seed word (or appending to "passphrase") the following
// :tgen:${CRC32(seed)}
// It is highly unlikely for users to create a wallet with that specific last word and add index to it
// We could leverage other fields such as native account index alone, but users may want to set that in future
// This solution is rather simple and if standard would get estabilished for this purpose it can be easily
// turned off and replaced with proper solution.

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:cw_core/pathForWallet.dart';
import 'package:cw_core/utils/print_verbose.dart';
import 'package:cw_core/wallet_info.dart';
import 'package:cw_core/wallet_type.dart';
import 'package:cw_zcash/src/util/crc32.dart';
import 'package:cw_zcash/src/zcash_wallet.dart';
import 'package:cw_zcash/src/zcash_wallet_service.dart';
import 'package:cw_zcash/src/warp_api_compat/legacy.dart';
import 'package:flutter/foundation.dart';
import 'package:path/path.dart' as p;

class ZcashTaddressRotation {
  ZcashTaddressRotation(this.accountIndex);
  final int accountIndex;

  static bool _isStarted = false;
  static bool _isCycleRunning = false;

  static const coin = ZcashWalletBase.coin;
  static const _stateFile = 'zec-taddr.json';
  static const _minUsablePool = 5;
  static const _sweepThreshold = 30000;
  static const _sweepFee = 10000;
  static final Map<int, int> _emptyCreateStreakByParent = <int, int>{};

  static String seedForOffset(final String seed) {
    final seedWords = seed.split(" ");
    if ([12, 24].contains(seedWords.length)) {
      seedWords.add("");
    }
    final lastI = seedWords.length - 1;
    final crc = CRC32.compute(seed);
    seedWords[lastI] += ":tgen:${crc}";
    return seedWords.join(" ");
  }

  static bool isSeedForWallet(final String? mainWallet, final String? subWallet) {
    if (mainWallet == null || subWallet == null) return false;
    final expected = seedForOffset(mainWallet.trim()).trim().replaceAll(RegExp(r'\s+'), ' ');
    final actual = subWallet.trim().replaceAll(RegExp(r'\s+'), ' ');
    return expected == actual;
  }

  static String normalizeSeed(final String? seed) =>
      seed?.trim().replaceAll(RegExp(r'\s+'), ' ') ?? '';

  static Map<int, List<Account>> rotationAccounts = {};
  static Map<int, List<Account>> rotationAccountsUsable = {};
  static Map<int, List<ShieldedTx>> shieldedAccountsTx = {};

  static Future<void> init() async {
    if (_isStarted) {
      return;
    }
    _isStarted = true;

    printV("deserialize previous state");
    final pfw = await pathForWalletTypeDir(type: WalletType.zcash);
    try {
      final f = File(p.join(pfw, _stateFile));
      if (!f.existsSync()) {
        f.writeAsBytesSync(serialize());
      }
      deserialize(f.readAsBytesSync());
    } catch (e) {
      printV("sfailed to deserialize state: $e");
    }

    Timer(const Duration(seconds: 5), () => unawaited(_runCycleGuarded()));
    Timer.periodic(const Duration(seconds: 35), (_) => unawaited(_runCycleGuarded()));
  }

  static Future<void> serializeToFile() async {
    final pfw = await pathForWalletTypeDir(type: WalletType.zcash);
    final f = File(p.join(pfw, _stateFile));
    f.writeAsBytesSync(serialize());
  }

  static Uint8List serialize() {
    final data = {
      "rotationAccounts": rotationAccounts.map(
        (final k, final v) =>
            MapEntry(k.toRadixString(16), v.map((final a) => base64.encode(a.toBytes())).toList()),
      ),
      if (kDebugMode)
        "_rotationAccounts": rotationAccounts.map(
          (final k, final v) =>
              MapEntry(k.toRadixString(16), v.map((final a) => a.toString()).toList()),
        ),
      "rotationAccountsUsable": rotationAccountsUsable.map(
        (final k, final v) =>
            MapEntry(k.toRadixString(16), v.map((final a) => base64.encode(a.toBytes())).toList()),
      ),
      if (kDebugMode)
        "_rotationAccountsUsable": rotationAccountsUsable.map(
          (final k, final v) =>
              MapEntry(k.toRadixString(16), v.map((final a) => a.toString()).toList()),
        ),
      "shieldedAccountsTx": shieldedAccountsTx.map(
        (final k, final v) =>
            MapEntry(k.toRadixString(16), v.map((final a) => base64.encode(a.toBytes())).toList()),
      ),
      if (kDebugMode)
        "_shieldedAccountsTx": shieldedAccountsTx.map(
          (final k, final v) =>
              MapEntry(k.toRadixString(16), v.map((final a) => a.toString()).toList()),
        ),
    };

    if (kDebugMode) {
      return utf8.encode(JsonEncoder.withIndent("    ").convert(data));
    }
    return utf8.encode(jsonEncode(data));
  }

  static void deserialize(final Uint8List bytes) {
    try {
      final Map<dynamic, dynamic> data = jsonDecode(utf8.decode(bytes));
      rotationAccounts = ((data["rotationAccounts"] as Map<String, dynamic>?) ?? {}).map(
        (final k, final v) => MapEntry(
          int.parse(k, radix: 16),
          (v as List).map((final a) => Account.fromBytes(atob(a))).toList(),
        ),
      );
      rotationAccountsUsable = ((data["rotationAccountsUsable"] as Map<String, dynamic>?) ?? {})
          .map(
            (final k, final v) => MapEntry(
              int.parse(k, radix: 16),
              (v as List).map((final a) => Account.fromBytes(atob(a))).toList(),
            ),
          );
      shieldedAccountsTx = ((data["shieldedAccountsTx"] as Map<String, dynamic>?) ?? {}).map(
        (final k, final v) => MapEntry(
          int.parse(k, radix: 16),
          (v as List).map((final a) => ShieldedTx.fromBytes(atob(a))).toList(),
        ),
      );
    } catch (e) {
      rethrow;
    }
  }

  static Uint8List atob(final String value) =>
      Uint8List.fromList(List<int>.from(base64.decode(value)));

  static Future<void> _runCycleGuarded() async {
    if (_isCycleRunning) {
      return;
    }
    _isCycleRunning = true;
    try {
      await createAndSweepTAddresses();
    } catch (e, s) {
      printV("cycle failed: $e");
      s.toString().split("\n").forEach(printV);
    } finally {
      _isCycleRunning = false;
    }
  }

  static Future<void> createAndSweepTAddresses() async {
    int chainHeight = 0;
    try {
      chainHeight = await WarpApi.getLatestHeight(coin);
    } catch (e) {
      printV("getLatestHeight failed: $e");
      return;
    }

    final dbHeight = WarpApi.getDbHeight(coin).unpack().height;
    if (chainHeight != dbHeight) {
      printV("waiting sync chain=$chainHeight db=$dbHeight");
      return;
    }

    await ZcashWalletService.runInDbMutex(() => WarpApi.refreshAccounts(coin));
    final accounts = WarpApi.getAccountList(coin);
    if (accounts.isEmpty) {
      rotationAccounts = {};
      rotationAccountsUsable = {};
      shieldedAccountsTx = {};
      await serializeToFile();
      return;
    }

    final idToAccount = <int, Account>{for (final account in accounts) account.id: account};
    final seedByAccountId = <int, String>{};
    final backupByAccountId = <int, Backup>{};

    for (final account in accounts) {
      await ZcashWalletService.runInDbMutex(
        () => WarpApi.refreshTransparentAccountCache(coin, account.id),
      );
      try {
        await WarpApi.transparentSync(coin, account.id, dbHeight);
      } catch (e) {
        printV("transparentSync: err: $e");
      }
      final backup = WarpApi.getBackup(coin, account.id);
      backupByAccountId[account.id] = backup;
      final seed = backup.seed;
      if (seed != null && seed.trim().isNotEmpty) {
        seedByAccountId[account.id] = seed;
      }
    }

    final expectedRotationNames = <String>{
      for (final account in accounts) CRC32.compute(account.id.toString()).toString(),
    };

    final parentIds = <int>[];
    for (final entry in seedByAccountId.entries) {
      final acc = idToAccount[entry.key];
      if (acc != null && expectedRotationNames.contains(acc.name)) {
        // Child accounts are named as CRC32(parentId); do not recurse.
        continue;
      }
      final words = entry.value.trim().split(RegExp(r'\s+'));
      if (![12, 13, 24, 25].contains(words.length)) {
        continue;
      }
      if (words.last.contains(':tgen:')) {
        continue;
      }
      parentIds.add(entry.key);
    }

    final hiddenAddresses = await _loadHiddenAndUsedAddresses();
    final newRotationAccounts = <int, List<Account>>{};
    final newRotationAccountsUsable = <int, List<Account>>{};
    final newShieldedTxByParent = <int, List<ShieldedTx>>{};

    bool createdAccounts = false;

    for (final parentId in parentIds) {
      final parentSeed = seedByAccountId[parentId];
      if (parentSeed == null) {
        continue;
      }

      final parentAccount = idToAccount[parentId];
      if (parentAccount == null) {
        continue;
      }
      final parentBackup = backupByAccountId[parentId];
      final parentIndex = parentBackup?.index;

      final expectedRotationName = CRC32.compute(parentId.toString()).toString();
      final normalizedParentSeed = normalizeSeed(parentSeed);
      final children = accounts.where((final account) {
        if (account.id == parentId) {
          return false;
        }
        final childSeedRaw = seedByAccountId[account.id];
        final normalizedChildSeed = normalizeSeed(childSeedRaw);
        final childIndex = backupByAccountId[account.id]?.index;
        final matchedBySeed =
            isSeedForWallet(parentSeed, childSeedRaw) ||
            (normalizedParentSeed.isNotEmpty && normalizedParentSeed == normalizedChildSeed);
        final matchedByName = account.name == expectedRotationName;
        final hasVerifiedIndex = childIndex is int && childIndex >= 0;
        return matchedBySeed && matchedByName && hasVerifiedIndex;
      }).toList()..sort((final a, final b) => a.id.compareTo(b.id));

      newRotationAccounts[parentId] = children;

      final txsForUi = <ShieldedTx>[];
      final usable = <Account>[];
      for (final child in children) {
        final childTxs = await WarpApi.getTxs(coin, child.id);
        txsForUi.addAll(childTxs);
        if (childTxs.isNotEmpty) {
          continue;
        }
        final childAddr = WarpApi.getTAddr(coin, child.id);
        if (childAddr.isEmpty) {
          printV("child ${child.id} has empty taddr, not usable");
          continue;
        }
        if (hiddenAddresses.contains(childAddr)) {
          continue;
        }
        usable.add(child);
      }

      newRotationAccountsUsable[parentId] = usable;
      newShieldedTxByParent[parentId] = txsForUi;

      final knownIndexes = <int>[];
      for (final child in children) {
        final idx = backupByAccountId[child.id]?.index;
        if (idx is int && idx >= 0) {
          knownIndexes.add(idx);
        }
      }
      knownIndexes.sort();
      final int? nextIndex = knownIndexes.isEmpty
          ? (parentIndex is int && parentIndex >= 0 ? parentIndex + 1 : null)
          : (knownIndexes.last + 1);

      if (usable.length < _minUsablePool) {
        if (nextIndex == null) {
          printV(
            "ZcashTaddressRotation: parent=$parentId skipping create due to missing verified index source (parentIndex=$parentIndex)",
          );
          await _trySweepChildren(parentAccount, children);
          continue;
        }
        final emptyCreateStreak = _emptyCreateStreakByParent[parentId] ?? 0;
        if (emptyCreateStreak >= 2) {
          printV(
            "ZcashTaddressRotation: parent=$parentId skipping create due to repeated empty taddr creations (streak=$emptyCreateStreak)",
          );
          await _trySweepChildren(parentAccount, children);
          continue;
        }
        final derivedSeed = seedForOffset(parentSeed);
        final name = CRC32.compute(parentId.toString()).toString();
        printV(
          "ZcashTaddressRotation: creating new transparent rotation account parent=$parentId name=$name nextIndex=$nextIndex",
        );
        final createdId = await ZcashWalletService.runInDbMutex(
          () => WarpApi.newAccount(coin, name, derivedSeed, nextIndex, transparentOnly: true),
        );
        await ZcashWalletService.runInDbMutex(
          () => WarpApi.refreshTransparentAccountCache(coin, createdId),
        );
        final createdTaddr = WarpApi.getTAddr(coin, createdId);
        if (createdTaddr.isEmpty) {
          _emptyCreateStreakByParent[parentId] = emptyCreateStreak + 1;
          printV(
            "ZcashTaddressRotation: created accountId=$createdId has empty taddr; keeping out of usable pool (streak=${_emptyCreateStreakByParent[parentId]})",
          );
        } else {
          _emptyCreateStreakByParent[parentId] = 0;
        }
        createdAccounts = true;
      }

      await _trySweepChildren(parentAccount, children);
    }

    rotationAccounts = newRotationAccounts;
    rotationAccountsUsable = newRotationAccountsUsable;
    shieldedAccountsTx = newShieldedTxByParent;
    await serializeToFile();

    if (createdAccounts) {
      printV("created new transparent rotation accounts");
      // Trigger an immediate follow-up cycle so newly-created accounts become visible quickly.
      Timer(const Duration(seconds: 2), () => unawaited(_runCycleGuarded()));
    }
  }

  static ShieldedTx reverseAmount(final ShieldedTx t) {
    final tt = t.unpack();
    tt.value = -tt.value;
    return tt;
  }

  static Account? accountForSeed(final String seed) {
    final accounts = WarpApi.getAccountList(coin);
    if (accounts.isEmpty) return null;
    for (int i = 0; i < accounts.length; i++) {
      final acc = accounts[i];
      final backup = WarpApi.getBackup(coin, acc.id);
      if (backup.seed == seed) {
        return acc;
      }
    }
    return null;
  }

  static String? addressForAccount(final int accountId, final Set<String>? hiddenAddresses) {
    final accs = rotationAccountsUsable[accountId] ?? [];
    for (int i = 0; i < accs.length; i++) {
      final addr = WarpApi.getTAddr(coin, accs[i].id);
      if (hiddenAddresses?.contains(addr) == true) {
        continue;
      }
      return addr;
    }
    return null;
  }

  static List<String>? allAddressesForAccount(final int accountId) {
    final acc = rotationAccounts[accountId];
    if (acc == null) {
      printV("Nothing found");
      return null;
    }
    for (int i = 0; i < acc.length; i++) {
      final b = WarpApi.getBackup(coin, acc[i].id);
      printV("$i. ${b.seed?.split(" ").last}, ${b.index}, ${WarpApi.getTAddr(coin, acc[i].id)}");
    }
    return acc.map((final a) => WarpApi.getTAddr(coin, a.id)).toList();
  }

  static List<String>? allUsedAddressesForAccount(final int accountId) {
    final acc = rotationAccounts[accountId]?.toList();
    if (acc == null) return null;
    final usableIds = (rotationAccountsUsable[accountId] ?? <Account>[])
        .map((final a) => a.id)
        .toSet();
    acc.removeWhere((final a) => usableIds.contains(a.id));
    for (int i = 0; i < acc.length; i++) {
      final b = WarpApi.getBackup(coin, acc[i].id);
      printV("$i. ${b.seed?.split(" ").last}, ${b.index}, ${WarpApi.getTAddr(coin, acc[i].id)}");
    }
    return acc.map((final a) => WarpApi.getTAddr(coin, a.id)).toList();
  }

  static Future<Set<String>> _loadHiddenAndUsedAddresses() async {
    final wis = await WalletInfo.selectList('type = ?', [WalletType.zcash.index]);
    final hidden = <String>{};
    for (final wi in wis) {
      hidden.addAll(await wi.getHiddenAddresses());
      hidden.addAll(await wi.getUsedAddresses());
    }
    return hidden;
  }

  static Future<void> _trySweepChildren(
    final Account parentAccount,
    final List<Account> children,
  ) async {
    for (final child in children) {
      int balance = 0;
      try {
        balance = await WarpApi.getTBalance(coin, child.id);
      } catch (e) {
        printV("getTBalance failed for ${child.id}: $e");
        continue;
      }
      if (balance < _sweepThreshold) {
        continue;
      }

      final targetAddress = WarpApi.getTAddr(coin, parentAccount.id);
      final recipient = Recipient.fromBytes(
        RecipientObjectBuilder(
          address: targetAddress,
          pools: 1,
          feeIncluded: true,
          amount: balance,
        ).toBytes(),
      );
      final fee = FeeT(fee: _sweepFee, minFee: 0, maxFee: 0, scheme: 0);
      try {
        final txPlan = await ZcashWalletService.runInDbMutex(
          () => WarpApi.prepareTx(coin, child.id, [recipient], 1, 0, 0, fee),
        );
        final txId = await ZcashWalletService.runInDbMutex(
          () => WarpApi.signAndBroadcast(coin, child.id, txPlan),
        );
        await ZcashWalletService.addShieldedTx(txId);
        printV("swept ${child.id} to ${parentAccount.id} tx=$txId");

        await Future<void>.delayed(const Duration(seconds: 2));
        return;
      } catch (e) {
        printV("sweep failed for ${child.id}: $e");
      }
      return;
    }
  }
}
